# Generated by Django 3.2.3 on 2021-05-18 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementingPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementing_partner_name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'implementing_partners',
                'ordering': ['implementing_partner_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_subsector_name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'subsectors',
            },
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='province',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AddField(
            model_name='partner',
            name='users_access',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default='9999-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='django_project.province'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectByProvinces',
        ),
        migrations.AddField(
            model_name='location',
            name='districts',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='province', chained_model_field='province', related_name='districs', to='django_project.District', verbose_name='districts'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='django_project.project'),
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.province'),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_partner',
            field=models.ManyToManyField(blank=True, to='django_project.ImplementingPartner'),
        ),
        migrations.AddField(
            model_name='project',
            name='other_subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_project.subsector'),
        ),
    ]
